### ISSUE TITLE
Update DockerCompose file for data persistance.

### ISSUE THREAD

**Issue by sehmuzc** [swe574-spring23/SWE574#12]
Currently there exists no volume on the DB side of the docker compose file, update the file so that data can stay even if docker is closed and opened again.

**Comment by sehmuzc** [comment]
Below parts have been added to the docker-compose yaml file.

```
 volumes:
      - pgdata:/var/lib/postgresql/data  # add a volume for persistent data
      
volumes:
  pgdata:  # define the volume for persistent data
```
